// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1 AND user_id = $2
`

type DeleteBookParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteBook(ctx context.Context, arg DeleteBookParams) error {
	_, err := q.db.ExecContext(ctx, deleteBook, arg.ID, arg.UserID)
	return err
}

const editBook = `-- name: EditBook :one
UPDATE books
SET updated_at = $2, 
    title = $3, 
    author = $4, 
    genre = $5, 
    page_max = $6, 
    page_current = $7, 
    description = $8, 
    note = $9, 
    rating = $10, 
    progress = $11, 
    ISBN = $12
WHERE id = $1
RETURNING id, user_id, updated_at, title, author, genre, page_max, page_current, description, note, rating, progress, isbn
`

type EditBookParams struct {
	ID          uuid.UUID
	UpdatedAt   time.Time
	Title       string
	Author      sql.NullString
	Genre       sql.NullString
	PageMax     sql.NullInt32
	PageCurrent sql.NullInt32
	Description sql.NullString
	Note        sql.NullString
	Rating      sql.NullInt32
	Progress    sql.NullString
	Isbn        sql.NullString
}

func (q *Queries) EditBook(ctx context.Context, arg EditBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, editBook,
		arg.ID,
		arg.UpdatedAt,
		arg.Title,
		arg.Author,
		arg.Genre,
		arg.PageMax,
		arg.PageCurrent,
		arg.Description,
		arg.Note,
		arg.Rating,
		arg.Progress,
		arg.Isbn,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UpdatedAt,
		&i.Title,
		&i.Author,
		&i.Genre,
		&i.PageMax,
		&i.PageCurrent,
		&i.Description,
		&i.Note,
		&i.Rating,
		&i.Progress,
		&i.Isbn,
	)
	return i, err
}

const getBooks = `-- name: GetBooks :many
SELECT id, user_id, updated_at, title, author, genre, page_max, page_current, description, note, rating, progress, isbn FROM books
`

func (q *Queries) GetBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UpdatedAt,
			&i.Title,
			&i.Author,
			&i.Genre,
			&i.PageMax,
			&i.PageCurrent,
			&i.Description,
			&i.Note,
			&i.Rating,
			&i.Progress,
			&i.Isbn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByUserID = `-- name: GetBooksByUserID :many
SELECT id, user_id, updated_at, title, author, genre, page_max, page_current, description, note, rating, progress, isbn FROM books WHERE user_id = $1
`

func (q *Queries) GetBooksByUserID(ctx context.Context, userID uuid.UUID) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UpdatedAt,
			&i.Title,
			&i.Author,
			&i.Genre,
			&i.PageMax,
			&i.PageCurrent,
			&i.Description,
			&i.Note,
			&i.Rating,
			&i.Progress,
			&i.Isbn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBook = `-- name: InsertBook :one
INSERT INTO books (id, user_id, updated_at, title, author, genre, page_max, page_current, description, note, rating, progress, ISBN)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, updated_at, title, author, genre, page_max, page_current, description, note, rating, progress, isbn
`

type InsertBookParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	UpdatedAt   time.Time
	Title       string
	Author      sql.NullString
	Genre       sql.NullString
	PageMax     sql.NullInt32
	PageCurrent sql.NullInt32
	Description sql.NullString
	Note        sql.NullString
	Rating      sql.NullInt32
	Progress    sql.NullString
	Isbn        sql.NullString
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, insertBook,
		arg.ID,
		arg.UserID,
		arg.UpdatedAt,
		arg.Title,
		arg.Author,
		arg.Genre,
		arg.PageMax,
		arg.PageCurrent,
		arg.Description,
		arg.Note,
		arg.Rating,
		arg.Progress,
		arg.Isbn,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UpdatedAt,
		&i.Title,
		&i.Author,
		&i.Genre,
		&i.PageMax,
		&i.PageCurrent,
		&i.Description,
		&i.Note,
		&i.Rating,
		&i.Progress,
		&i.Isbn,
	)
	return i, err
}
