openapi: 3.1.0
info:
  title: Catalog and Progress Tracker Book API
  version: 1.0.0
servers:
  - url: http://103.23.198.215/api/v1
    description: Backend API
components:
  securitySchemes:
    BearerAuth:          
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    ErrorObject:
      type: object
      properties:
        error:
          type: string
          examples: ["Error Message"]
    BookObject:
      type: object
      properties:
        id:
          type: string
          examples: ["2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e"]
        updated_at:
          type: string
          format: date-time
          examples: ["2026-05-24T10:35:00Z"]
        title: 
          type: string
          examples: ["Atomic Habits"]
        author:
          type: string
          examples: ["James Clear"]
        genre:
          type: string
          examples: ["Self-Improvement"]
        page_max:
          type: integer
          examples: [320]
        page_current:
          type: integer
          examples: [120]
        description:
          type: string
          examples: ["Cara mudah dan terbukti untuk membangun kebiasaan baik dan menghilangkan kebiasaan buruk."]
        note:
          type: string
          examples: ["Sangat direkomendasikan untuk seseorang yang ingin membangun habit positif"]
        rating:
          type: integer
          examples: [4]
        progress:
          type: string
          examples: ["sedang"]
        isbn:
          type: string
          examples: [9780525538288]
    UserResponse:
      type: object
      properties:
        id:
          type: string
          examples: ["de230675-3d8e-42cc-a3c4-e742e98b5687"]
        username:
          type: string
          examples: ["budi_sanjaya"]
        created_at:
          type: string
          format: date-time
          examples: ["2026-05-24T11:03:00Z"]

paths:
  /healthz:
    get:
      summary: Check if REST server is running correctly
      responses:
        '200':
          description: REST API server is running.
  /books:
    get:
      summary: get user's books.
      security: 
        - BearerAuth: []
      responses:
        '200':
          description: Success to get user's book
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/BookObject'
        '401': 
          description: Authorization failed
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
    post:
      summary: Store list of books of user to database
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BookObject'
      responses:
        '200':
          description: "Success to save user's books"
        '401': 
          description: Authorization failed
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
    put:
      summary: Edit user's books
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BookObject'
      responses:
        '200':
          description: "Success to edit user's books"
        '401': 
          description: Authorization failed
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
  /books/delete:
    post:
      summary: delete user's books
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                examples: ["7954df09-7c41-4954-8a3b-2df613f11e1c"]
      responses:
        '200':
          description: Success
        '400':
          description: Invalid Book's ID
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
        '401': 
          description: Authorization failed
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
  /book/{bookId}:
    delete:
      summary: Delete user's book.
      security:
        - BearerAuth: []
      parameters:
        - name: bookId
          in: path
          required: true
          description: Unique ID of the book
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: Invalid Book's ID
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
        '401': 
          description: Authorization failed
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'

  /user/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  examples: ["budi_sanjaya"]
                password:
                  type: string
                  format: password
                  examples: ["Rahasia123!"]
      responses:
        '201':
          description: Success to register user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: username not available
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
        '500':
          description: internal server error
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
  /user/login:
    post:
      summary: Login to get new JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  examples: ["budi_sanjaya"]
                password:
                  type: string
                  format: password
                  examples: ["SuperDuperSecret123!"]
      responses:
        '200':
          description: Success to get JWT Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    examples: ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."]
        '401':
          description: Wrong username or password
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                type: object
                item:
                  $ref: '#/components/schemas/ErrorObject'
